README
=> Remove README reference to site URL until ready.

README.md
Not too exciting. https://github.com/louquillio/draco/blob/syntax-highlight-readme/README.md
=> Syntax-highlight code blocks, README.md

README.md
No TOC auto-generation for README.md, so created manually. If headings change, TOC must be manually updated.
=> Add readme.md toc

README.md
Also fix long lines and other cosmetics.
=> Edit README.md for consistent usage and formatting.

javascript/example/DRACOLoader.js
Just a small fix to make sure the error has the correct message.
=> Make sure errorMsg is defined

core/draco_version.h
=> Increase version to "0.10.1"

docs/_config.yml, docs/index.md, docs/spec/README.md
See commit msgs. Hopefully this works the first time.
=> Fix baseurl and paths

docs/spec/attributes.decoder.md, docs/spec/draco.decoder.md, docs/spec/edgebreaker.decoder.md, docs/spec/edgebreaker.hole.and.topology.md, docs/spec/edgebreaker.traversal.decoder.md, docs/spec/edgebreaker.traversal.valence.decoder.md, docs/spec/index.md, docs/spec/mesh.decoder.md, docs/spec/mesh.prediction.scheme.parallelogram.md, docs/spec/metadata.decoder.md, docs/spec/rans.bit.decoder.md, docs/spec/rans.decoding.md, docs/spec/sequential.quantization.attribute.decoder.md, docs/spec/symbol.decoding.md, docs/spec/variable.descriptions.md
This PR is associated with #134.
=> Update bitstream spec

README.md, docs/spec/README.md
ocupop did a nice job with this.
=> Credit Draco logo designers.

docs/_layouts/home.html
Should resize responsively. Cued to 00:33.
=> Embed YT Draco clip on homepage.

docs/_includes/analytics.html, docs/_layouts/home.html, docs/_layouts/spec.html
new file:   docs/_includes/analytics.html
modified:   docs/_layouts/home.html
modified:   docs/_layouts/spec.html
=> Add Google Analytics tracker; apply via templating `include`.

docs/spec/02.00.00.terms.md, docs/spec/03.00.00.symbols.md, docs/spec/04.00.00.conventions.md
=> Remove or comment some spec placeholder text.

docs/assets/css/spec-style.sass, docs/spec/02.00.00.terms.md
Remove CSS artifacts from spec stylesheet. Tweak a table style.
=> Remove unused CSS.

docs/spec/mesh.prediction.scheme.parallelogram.md
MeshPredictionSchemeParallelogramShared
=> Remove a stray heading.

docs/spec/00.00.04.abstract.md, docs/spec/01.00.00.scope.md
=> Provide a (temporary) link from the spec draft to its README.

CMakeLists.txt
=> Change Cmake hint so building will work

src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_portable_decoder.h, src/draco/compression/attributes/sequential_attribute_decoder.cc, src/draco/io/mesh_io.cc, src/draco/io/point_cloud_io.cc, src/draco/tools/draco_decoder.cc
there is definitely a bug somewhere that led to #171, perhaps shouldn't be included if actual bug is fixed.
=> fix for #108 and workaround to avoid crash in #171

src/draco/compression/attributes/sequential_attribute_decoder.cc, src/draco/io/mesh_io.cc, src/draco/io/point_cloud_io.cc, src/draco/javascript/emscripten/decoder_webidl_wrapper.cc, src/draco/javascript/emscripten/decoder_webidl_wrapper.h, src/draco/tools/draco_decoder.cc
=> Add decoder_webidl_wrapper sources.

testdata/mat_test.mtl
=> Added test material file

docs/spec/variable.descriptions.md
=> Added variables section to spec.

docs/spec/04.00.00.conventions.md, docs/spec/prediction.wrap.transform.md, docs/spec/sequential.integer.attribute.decoder.md
=> A few small fixes for the spec.

docs/spec/00.00.02.authors.md, docs/spec/02.00.00.terms.md, docs/spec/attributes.decoder.md, docs/spec/index.md, docs/spec/prediction.normal.decoder.md, docs/spec/prediction.normal.transform.md, docs/spec/prediction.texcoords.decoder.md, docs/spec/sequential.normal.attribute.decoder.md, docs/spec/vector.md
=> Finalizing the bitstream spec.

docs/spec/sequential.decoder.md
This addresses a comment in KhronosGroup/glTF#1114
=> spec: Add connectivity_method == 0 to Sequential decoder

docs/_config.yml, docs/_layouts/home.html, docs/_layouts/spec-page.html
Looking for a relative URL scheme that works locally and on gh-pages.
=> Fix relative URL breakage with site.baseurl="/draco". Hopefully.

docs/spec/edgebreaker.decoder.md
- This associated with KhronosGroup/glTF#1114
=> Spec Update EdgeBreaker header to 2.2

docs/spec/attributes.decoder.md, docs/spec/edgebreaker.traversal.md, docs/spec/edgebreaker.traversal.valence.md, docs/spec/variable.descriptions.md
=> Spec update Valence traversal to 2.2

docs/spec/prediction.decoder.md, docs/spec/prediction.multi.parallelogram.decoder.md, docs/spec/prediction.normal.decoder.md, docs/spec/prediction.parallelogram.decoder.md, docs/spec/prediction.texcoords.decoder.md
- This addresses a comment in KhronosGroup/glTF#1114
=> Spec: Change to use array copy notation

docs/spec/04.00.00.conventions.md, docs/spec/edgebreaker.decoder.md, docs/spec/edgebreaker.traversal.prediction.degree.md, docs/spec/prediction.texcoords.decoder.md
- This addresses a comment in KhronosGroup/glTF#1114
=> Spec: Update functions based on std::vector

docs/spec/04.00.00.conventions.md, docs/spec/edgebreaker.decoder.md, docs/spec/prediction.multi.parallelogram.decoder.md, docs/spec/prediction.parallelogram.decoder.md, docs/spec/prediction.wrap.transform.md, docs/spec/rans.decoding.md
- This addresses some comments in KhronosGroup/glTF#1114
=> Spec clean up

docs/spec/edgebreaker.decoder.md
- This addresses a comment in KhronosGroup/glTF#1114
=> Spec: Add GetNumComponents function

docs/spec/edgebreaker.decoder.md, docs/spec/variable.descriptions.md
- This addresses a comment in KhronosGroup/glTF#1114
=> Spec: Add ProcessInteriorEdges function

docs/spec/edgebreaker.decoder.md, docs/spec/edgebreaker.traversal.md, docs/spec/variable.descriptions.md
- This change is in bitstream 2.2.
=> Spec: Change Face configuration to use RansBitCoder

docs/spec/04.00.00.conventions.md, docs/spec/edgebreaker.traversal.md, docs/spec/metadata.decoder.md, docs/spec/rans.decoding.md
=> Spec: Update buffer size reading

docs/spec/04.00.00.conventions.md
=> Spec: Update some type info

docs/spec/rans.decoding.md
=> Spec: Simplify DecodeTaggedSymbols function

docs/spec/boundary.decoder.md, docs/spec/edgebreaker.decoder.md, docs/spec/prediction.decoder.md, docs/spec/prediction.multi.parallelogram.decoder.md
=> Spec: Small cleanup

docs/spec/variable.descriptions.md
=> Spec add edge_breaker_symbol_to_topology_id

docs/spec/rans.decoding.md, docs/spec/sequential.decoder.md, docs/spec/variable.descriptions.md
=> Spec: Add some named constants

docs/spec/rans.decoding.md, docs/spec/variable.descriptions.md
=> Spec: Fix Tagged Symbols constant

docs/spec/edgebreaker.decoder.md
=> Spec: Initialize curr_att_dec and curr_att

docs/spec/04.00.00.conventions.md, docs/spec/edgebreaker.decoder.md, docs/spec/rans.decoding.md
=> Spec: Clarify when bit reading is done.

docs/spec/edgebreaker.decoder.md, docs/spec/variable.descriptions.md
=> Spec: Fix handling of split symbol id during topology split.

docs/spec/edgebreaker.decoder.md, docs/spec/variable.descriptions.md
=> Spec: Fix standard edgebreaker symbol buffer

docs/spec/04.00.00.conventions.md
=> Spec: Clarify uninitialized values of opposite_corners_

docs/spec/04.00.00.conventions.md
=> Spec: Clarifiy array element assignment.

docs/spec/attributes.decoder.md
=> Spec: Change C++ variable initialization

docs/spec/sequential.integer.attribute.decoder.md
=> Spec: Remove static_cast

docs/spec/rans.decoding.md
=> Spec: Fix DecodeTaggedSymbols

docs/spec/edgebreaker.decoder.md, docs/spec/prediction.texcoords.decoder.md
=> Spec: Remove references to pointers

docs/spec/prediction.decoder.md
- Associated with KhronosGroup/glTF#1114
=> Spec: Update variables to reflect final 2.2 bitstream

docs/spec/metadata.decoder.md, docs/spec/prediction.decoder.md, docs/spec/prediction.multi.parallelogram.decoder.md, docs/spec/prediction.normal.decoder.md, docs/spec/prediction.texcoords.decoder.md
- Associated with KhronosGroup/glTF#1114
=> Spec: Line length clean up

docs/spec/edgebreaker.traversal.md, docs/spec/edgebreaker.traversal.prediction.degree.md, docs/spec/prediction.multi.parallelogram.decoder.md
- Associated with KhronosGroup/glTF#1114
=> Spec: Remove C++ initialization

README.md
=> Fixing misprint in js-decoder code-list.

CONTRIBUTING.md
=> Fix markdown issues with links

CMakeLists.txt
Enable all Compile Optimization by setting according compiler flags. (Visual Studio tested, gcc and other should work properly, but untested)
=> Optional Compiler Optimization

cmake/compiler_flags.cmake, src/draco/core/options.h, src/draco/io/obj_decoder.cc, src/draco/io/ply_decoder.cc
Changes required to build for Android ARMv8 with Clang and LibC++,  fixes for #306.  If I can get feedback on more platform neutral ways to fix these issues I will apply and update the PR.
=> Fixing Android ArmV8/Clang/LibC++ build

docs/spec/edgebreaker.traversal.valence.md
Reference:
https://github.com/KhronosGroup/glTF/issues/1114#issuecomment-350043164
=> Fix spec valence start

cmake/toolchains/arm-ios-common.cmake, cmake/toolchains/arm64-ios.cmake, cmake/toolchains/armv7-ios.cmake, cmake/toolchains/armv7s-ios.cmake
Rubber stamp? These work on my machine...
=> Arm ios toolchains

README.md
- Add ANDROID_STL configuration.
- Remove flags that are no longer needed.
=> Update README info for Android Studio integration.

unity/DracoMeshLoader.cs
I'm trying to decode 10 million mesh face, which is very slow.But not of Draco, it was slow to split mesh in Unity, so I did the unity split mesh optimization.And with multiple threads, there is almost no overhead for the main thread.
200s->8s
=> Accelerating Unity split mesh.

unity/DracoMeshLoader.cs
Improved formatting and variable naming for DracoMeshLoader.cs
- added back tabs
- renamed some variables to better reflect their intended use
=> Updated DracoMeshLoader.cs

javascript/example/DRACOLoader.js
See https://github.com/mrdoob/three.js/pull/14002.
=> THREE.DRACOLoader: Support attribute type map.

CMakeLists.txt
Fixes https://github.com/google/draco/issues/328
=> Fix NMake builds with BUILD_SHARED_LIBS enabled.

src/draco/compression/point_cloud/algorithms/point_cloud_compression_method.h
Same as https://github.com/google/highwayhash/pull/81 ;-)
=> Hyperlink DOI to preferred resolver

docs/_includes/footer.html
Hopefully also kicks off a gh-pages rebuild.
=> Update page footer template to display current year in copyright legend.

src/draco/core/hash_utils.h
=> Fix gcc11 compile error

README.md, unity/README.md
I moved my repository back go github, where I plan to update it.
=> fix: Updated link to alternative Unity package

src/draco/tools/draco_decoder.cc, src/draco/tools/draco_encoder.cc
Add -v arg that causes the tools to print version and exit when specified.
=> Add version string output to cli tools.

src/draco/tools/draco_decoder.cc, src/draco/tools/draco_encoder.cc
Reverts google/draco#626: PR submitter did not sign CLA.
=> Revert "Add version string output to cli tools."

CMakeLists.txt, cmake/draco_targets.cmake
=> Set VERSION and SOVERSION for all targets as appropriate

src/draco/io/parser_utils.cc
Fixes https://github.com/google/draco/issues/706
=> Add include of limits in parser_utils.cc

cmake/draco_build_definitions.cmake
This should have been included in v1.4.3.
Fixes https://github.com/google/draco/issues/754
=> Bump LT_CURRENT.

cmake/draco_install.cmake, src/draco/tools/install_test/CMakeLists.txt, src/draco/tools/install_test/test.py
Also updates the install test to correctly set prefix and allow
CMake's built-in search functionality to work properly.
=> Correct the install location for CMake configuration files.

src/draco/io/file_writer_utils.cc
file_writer_utils.cc - fix preprocessor check and wrong path check
=> Win32: Warning on wrong preprocessor syntax Issue #1031

.github/workflows/ci.yml, README.md, docs/_layouts/home.html, docs/_layouts/spec-page.html, docs/spec/README.md, javascript/npm/draco3d/README.md, javascript/npm/draco3dgltf/README.md
=> replace references to 'master' with 'main'
