javascript/example/DRACOLoader.js
The DRACOLoader.js file was ignoring texture coordinates (uvs) when loading objects. This pull request correctly loads the texture coordinates and applies them to the BufferGeometry.
=> Javascript loader: load texture coordinates (uvs)

io/obj_decoder.cc
Fix loading of OBJ file with minus index.
Sample:
http://graphics.cs.williams.edu/data/meshes.xml
* Cube
* Dragon
=> Fix loading of OBJ file with minus index.

CMakeLists.txt
Installs includes, libs, and executables.
Based on https://github.com/google/draco/pull/21
=> Add install rule to cmake build.

javascript/example/DRACOLoader.js
Current example loader will not display vertex colors correctly, since color attribute data need to be normalized as a fraction of 255.
=> fixed threejs example vertex color normal

javascript/example/README, javascript/example/webgl_loader_draco.html
I'd like to suggest simplifying the steps required to get an example running for newer users.
The proposed change would link to the latest stable version of three.js (r84) from a CDN, and use a relative link to the existing `draco_decoder.js` file.
=> Simplify steps required to run example.

core/vector_d.h
Adding cmath include to fix OSX build (issue #83).
=> Fix build for sqrt usage in vector.

javascript/example/DRACOLoader.js
I wanted to avoid making another instance of DracoModule just to check a version, so this PR also exposes a singleton decoder with a static factory method.
(good use case for adding `?w=1` to the URL to ignore whitespace in diffs)
=> Expose .isVersionSupported() method on THREE.DRACOLoader.

docs/spec/README.md
For building docs locally, there's no need to specify
an alternate `--baseurl` as long as `jekyll serve` is
issued from the `/docs` directory, as indicated in
README.md.
Removed --baseurl guidance and emphasized README.md
instructions.
=> No need to use --baseurl argument

docs/index.md, docs/spec/README.md, docs/spec/index.md
Though homepage is rendered completely from a template,
it still needs an index.md to generate.
Also change subpage breadcrumb links to relative, so they
work in the GitHub Pages context. For example "/" points
to the Google Org's home rather than Draco's home, so use
"..", etc.
=> Add empty homepage index.md

docs/_layouts/home.html
YT linking tool offers custom start times on shared links but not embeds. Hackable, though.
=> Fix homepage video cue point.

docs/_layouts/home.html
Homepage "jumbotron" (logo + statement) should align well on all
viewport sizes. Specifically on phones (<768px), logo and statement
should both take full width and stack (and center).
At tablet widths, distribute 1/3:2/3. At larger widths, 1/4:3/4.
=> At extra small widths (phones), stack jumbotron elements.

docs/_includes/footer.html, docs/_layouts/spec-page.html, docs/assets/css/spec-style.sass, docs/spec/README.md, docs/spec/attributes.decoder.md, docs/spec/core.functions.md, docs/spec/draco.decoder.md, docs/spec/edgebreaker.decoder.md, docs/spec/edgebreaker.hole.and.topology.md, docs/spec/edgebreaker.traversal.decoder.md, docs/spec/edgebreaker.traversal.valence.decoder.md, docs/spec/index.md, docs/spec/metadata.decoder.md, docs/spec/prediction.scheme.wrap.transform.md, docs/spec/rans.bit.decoder.md, docs/spec/sequential.attribute.decoder.md, docs/spec/sequential.attributes.decoders.controller.md, docs/spec/sequential.integer.attribute.decoder.md, docs/spec/sequential.quantization.attribute.decoder.md, docs/spec/symbol.decoding.md
* Create template for spec pages
* Adapt syntax-table styles to Bootstrap
* Reposition type/size annotations at col 86 (and update README.md)
* Let Bootstrap style breadcrumb trails
* Unrelated: abstract footer to an _include
=> Adapt spec-related pages to Bootstrap.

docs/spec/00.00.05.toc.md
Spec's TOC is very long. This adds a button to toggle collapse-reveal
of TOC. Initially collapsed.
=> Make spec table of contents collapsible.

javascript/npm/draco3d/README.md, javascript/npm/draco3d/draco_nodejs_example.js, javascript/npm/draco3d/package.json
Couple small changes here:
- Replace `nodejs` with more common `node` executable name.
- Add GitHub URL to npm package, so cross-link will appear on [package description](https://www.npmjs.com/package/draco3d).
- Simplify example script a bit, reusing code shared among attributes, and fixing a couple let/const issues.
=> Simplify Node.js usage example.

docs/assets/css/spec-style.sass
Syntax tables rely on precise monospace font rendering
with regard to font-size and especially line-height.
This applies more specific selectors, in an attempt to
have Firefox render identically to Chrome.
=> Fix cross-browser monospace font rendering (Firefox CSS).

docs/assets/css/spec-style.sass
CSS generated content, using `:before`.
=> Add a "Type" heading on second column of syntax tables.

CMakeLists.txt
The way header files are glob resulted in two additional directories
being nested in include.
=> Clean up superfluous directories draco/src in include

src/draco/attributes/geometry_attribute.h
Added support for 64bit integer, 64bit float and boolean in
ConvertValue
Reordered the case label to match those in the enum
for easier maintenance in the long run
=> Added handling for all enum in draco::DataType

README.md, javascript/npm/draco3d/draco_nodejs_example.js
Allows draco3d to be called from same directory or npm package
If you follow the [instructions on NPM readme](https://github.com/google/draco/blob/master/javascript/npm/draco3d/README.md#npm-package) you will find you need to edit the file because `./draco3d` is not a file when you copy it out of the `node_module` file with `cp node_modules/draco3d/draco_nodejs_example.js .`
This seems like the simpler solution than adding an instruction to open the file in a text editor and fix it
=> npm: fixed npm example

src/draco/io/obj_decoder.cc
Reported [here](https://github.com/google/draco/issues/178).
The bug is that all sub object id of vertex are same.
=> Fix sub object id bug

.travis.yml, CMakeLists.txt
Builds and runs draco_tests on linux (clang and gcc) and osx (clang).
=> Add basic Travis-CI support.

docs/spec/prediction.decoder.md
- Removed unused prediction mode from constrained multi.
- Removed unused prediction mode from geometric normal.
- Changed num_orientations from I32 to varUI32 in tex coords.
- Removed unused center_value from normal octahedron.
=> Cleanup pred schemes for 2.2

docs/spec/edgebreaker.decoder.md, docs/spec/variable.descriptions.md
- The split_edge was removed from bitstream 2.2 as it was not used
during decoding.
=> Spec: Remove split_edge from bitstream 2.2

docs/spec/edgebreaker.traversal.md, docs/spec/prediction.decoder.md
- Bitstream 2.2 changed the RansBitCoder size from UI32 to varUI32.
=> Spec: Change RansBitDecoder size to varUI32

docs/spec/edgebreaker.traversal.md, docs/spec/edgebreaker.traversal.valence.md
- This change is in bitstream 2.2.
=> Spec: Remove symbol buffer from Valence EdgeBreaker

docs/spec/edgebreaker.traversal.md
- This change is in bitstream 2.2.
=> Spec: Change DirectBitCoder size to varUI64

docs/spec/attributes.decoder.md, docs/spec/boundary.decoder.md, docs/spec/edgebreaker.decoder.md, docs/spec/prediction.decoder.md, docs/spec/prediction.normal.decoder.md, docs/spec/prediction.parallelogram.decoder.md, docs/spec/prediction.texcoords.decoder.md, docs/spec/rans.decoding.md, docs/spec/variable.descriptions.md
- Initialized last_vert_added
- Normalized usage of ans_decoder_
- Removed parsing of num_new_vertices
- Removed num_corners
- Added prediction_rans_data_buffer
- Fixed spelling of orientations
- Replaced SubtractInt64Vectors with SubtractVectors
- Initialized pred_vals
- Changed point_to_corner_map from array to counter
- Addresses comments in KhronosGroup/glTF#1114
=> Spec: Addressing comments

src/draco/io/obj_decoder.cc, src/draco/io/ply_decoder.cc
This PR fixes compilation error with VS2015:
1>C:\draco\io\ply_decoder.cc(40): error C2666: 'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
1>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(105): note: could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
1>         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(100): note: or       'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &) const'
=> Do not assign std::streampos to std::streamoff

javascript/example/DRACOLoader.js, javascript/example/README.md, javascript/example/webgl_loader_draco.html, javascript/example/webgl_loader_draco_advanced.html
Simplifies loading of decoder source files:
1. Remove `setTimeout()` polling for the decoder module.
2. Use static `.setDecoderPath()` and `.setDecoderConfig()` methods to have a more standard JS API. I think this makes the singleton decoder lifecycle feel more natural.
3. Use Promises for internal methods, while keeping the same callback-based public API, which just simplifies the code a bit. This is how THREE.GLTFLoader works as well.
4. Don't automatically fetch the decoder source files (which might slow down page loading), but allow users to do that themselves if they prefer.
Updated usage example:
```js
// (Optional) Change decoder source directory (defaults to './').
THREE.DRACOLoader.setDecoderPath('./path/to/decoder/');
// (Optional) Use JS decoder (defaults to WebAssembly if …
```
=> DRACOLoader: Simplify decoder source loading.

javascript/example/DRACOLoader.js
Calling `decodeDracoFile` currently caches the `attributeUniqueIdMap` on the instance, meaning:
- call `decodeDracoFile` with attribute map
- async request (1) begins
- call `decodeDracoFile` with a new attribute map, overriding `this.attributeUniqueIdMap`
- async request (2) begins
- async request (1) completes, begins decoding using the wrong attribute map
In this situation there will be issues in glTF assets containing multiple meshes. See https://github.com/donmccurdy/three.js/pull/6 for full context.
=> DRACOLoader: Support requests for multiple files in parallel

docs/Gemfile.lock
critical security vulnerability has been found in < 1.8.1
=> Updated nokogiri dependency to >= 1.8.1

.travis.yml
Really this time. Previous commit installed the package, but
did not change compilers.
=> Use g++4.9 for Travis GCC builds.

CMakeLists.txt
I needed the following changes to successfully build with -DBUILD_SHARED_LIBS=ON
Otherwise got the position independent code error.
`relocation R_X86_64_32 against .rodata.str1.1 can not be used when making a shared object; recompile with -fPIC`
There's several ways to do the same so this is just a suggestion.
=> Fix BUILD_SHARED_LIBS=ON GCC build

src/draco/core/macros.h
GCC will not compile with multi-line comments and `-Wall`.
=> Remove multi-line comment from macros.h

README.md, cmake/util.cmake
Updates require_var() and set_variable_if_unset() to use the
environment values for named variables.
CMake processes toolchain files multiple times, and on some
processing runs cache variables are not available. Environment
variables are always available.
=> Require Android NDK path in environment.

src/draco/unity/draco_unity_plugin.cc, unity/DracoMeshLoader.cs
The alpha colour for vertex colours wasn't getting decompressed. This seems to be working, but I haven't run any automated tests or done extensive testing for this.
=> retain alpha vertex colour attribute when decompressing unity mesh

CMakeLists.txt
Downstream users sometimes need the standard Draco library targets,
even when building in Emscripten. Add the flag ENABLE_JS_GLUE, which
defaults to ON. When turned OFF, the standard Draco library targets
will still be built within an Emscripten build.
Also do some whitespace clean up while working in CMakeLists.txt.
https://github.com/google/draco/issues/407
=> Add a flag that allows building standard targets in Emscripten.

CMakeLists.txt, Makefile.decoder.emcc, README.md
The current JavaScript decoder module fails when run in IE11. 
This allows an `IE_COMPATIBLE` variable to be set when generating the cmake files in order to build a module that works in IE11 by providing polyfills, at a small hit to module size (1MB), with the solution proposed in https://github.com/kripken/emscripten/issues/6204
=> Add a flag for cmake to generate IE11 compatible JS decoder modules

src/draco/attributes/geometry_indices.h
Remove extra semicolons after macros which are reported as warnings when compiling with `pedentic` flag.
=> Allow to compile with Draco without warnings

src/draco/compression/attributes/point_d_vector.h
This PR fixes a MSCV compiler warning.
=> attributes/point_d_vector: Prevent a singend/unsigned mismatch

.travis.yml
Update the linux jobs to use Xenial. This simplifies our setup: We no longer need to check for the presence of packages other than ccache and cmake.
=> TravisCI: Use newer linux images.

CMakeLists.txt
Changed the library type from MODULE to STATIC for dracodec_unity IOS only. For other platforms it stays MODULE.
Tested with CMake 3.14.5 (has built-in iOS toolchain)
```bash
cmake .. -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=armv7\;armv7s\;arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.0 -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO -DBUILD_UNITY_PLUGIN=ON
```
=> Fix: Unity requires static libs for iOS.

src/draco/compression/decode.cc, src/draco/compression/encode_base.h, src/draco/compression/expert_encode.cc, src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc, src/draco/compression/mesh/mesh_sequential_encoder.cc, src/draco/compression/point_cloud/point_cloud_decoder.cc, src/draco/compression/point_cloud/point_cloud_encoder.cc, src/draco/core/status.h, src/draco/core/status_test.cc, src/draco/io/mesh_io.cc, src/draco/io/obj_decoder.cc, src/draco/io/ply_decoder.cc, src/draco/io/ply_decoder_test.cc, src/draco/io/point_cloud_io.cc
Change the name to avoid conflict with Windows headers.
=>  Rename Status::ERROR to Status::DRACO_ERROR.

CMakeLists.txt
We rely upon CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS for windows DLL
support, but we must defer the BUILD_SHARED_LIBS check until after the
plugin args are checked since the plugin checks can enable BUILD_SHARED_LIBS.
Without this change Visual Studio will not create import libs for the draco DLLs,
and that breaks the build.
=> draco cmake: Defer windows shared lib check until after plugin checks.

CMakeLists.txt
Avoid a confusing failure mode for javascript builds by requiring that
points at an existing directory. Prevents failure of custom
commands late in the configure and build processes.
=> draco cmake: Require the EMSCRIPTEN environment variable.

src/draco/javascript/emscripten/decoder_webidl_wrapper.cc, src/draco/javascript/emscripten/decoder_webidl_wrapper.h, src/draco/javascript/emscripten/draco_web_decoder.idl
We need this to read some internal metadata on our geometries. If possible, we would like to get this deployed through an official release soonish.
=> Add MetadataQuerier.GetIntEntryArray to JavaScript bindings

cmake/draco_features.cmake
- this prevents unnecessary decode.cc rebuilds after each CMake run
=> Update CMake-generated headers only when their content changes

src/draco/core/draco_test_utils.cc
Apparently MSVC runtime in text mode interprets 0x1a as end of file. So binary mode is necessary for reading file.
=> Fix unit test golden file reading (#471)

src/draco/javascript/emscripten/decoder_webidl_wrapper.cc, src/draco/javascript/emscripten/decoder_webidl_wrapper.h, src/draco/javascript/emscripten/draco_web_decoder.idl
Example Usage (TS code):
```
function _getUint16Array(
length: number,
decoder: DecoderInstance,
mesh: MeshInstance,
attributeId: number
): Uint16Array {
const nBytes = length * 2;
const ptr = draco._malloc(nBytes);
const attribute = decoder.GetAttribute(mesh, attributeId);
if (!decoder.GetAttributeUInt16ArrayForAllPoints(mesh, attribute, ptr, length)) {
throw "GetAttributeUInt16ArrayForAllPoints failed";
}
const array = new Uint16Array(draco.HEAPU8.buffer, ptr, length).slice();
draco._free(ptr);
return array;
}
```
=> Add TypedArray JS API for selected data types

src/draco/point_cloud/point_cloud.cc
This PR adds a missing cast to eliminate a compiler warning.
=> point_cloud: Fix compiler warning

cmake/util.cmake
- this prevents unnecessary rebuilds after each CMake run
=> Update CMake-generated dummy sources only when their content changes

CMakeLists.txt
This is a workaround for two issues with CMake's Xcode generator:
- Setting the LINK_LANGUAGE property does not work.
- Library targets that only combine other object files do not build in
Xcode because of some other issue in the generator. They don't fail
at build time: Xcode just does not build them.
The combined behavior of the two issues forces addition of dummy source
files to the listed targets.
Fixes issue https://github.com/google/draco/issues/593
=> draco: Add dummy sources to draco, dracodec, and dracoenc.

README.md
Super minor, but I was looking at the repo and noticed the logo was blurry, poked around a bit and found the svg version already in the repo, so why not try and use it for the README?
=> Uses SVG logo in README

cmake/draco_targets.cmake
Older CMake releases don't support empty list variables with list(FILTER).
=> draco: Fix empty list handling in older CMakes.

cmake/draco_targets.cmake
=> Fix typo in CMake macro draco_add_executable()

CMakeLists.txt, cmake/draco_build_definitions.cmake, cmake/draco_install.cmake, cmake/draco_targets.cmake
Mingw-w64 (and Cygwin) uses the following extension schema for generated libraries:
- Shared library: `.dll`
- Import library:  `.a.dll`
- Static library: `.a`
Notice that there is no basename collision between shared and static libraries, so it is safe to support generating both types at the same time.
The basename collision issue happens only in MSVC (to the best of my knowledge).
=> Support building mingw static and dynamic at the same time

cmake/draco_targets.cmake
Error must have been introduced with #676
Using the Ninja generator and Apple clang version 12.0.0 (clang-1200.0.32.29)
The error before was:
```
[build] : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -bundle -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.4.1 -o dracodec_unity.bundle/Contents/MacOS/dracodec_unity CMakeFiles/draco_unity_plugin.dir/src/draco/unity/draco_unity_plugin.cc.o  libdraco.a && :
[build] clang: error: invalid argument '-compatibility_version 1.0.0' only allowed with '-dynamiclib'
```
=> fix: Linking dracodec_unity macOS bundle works again

src/draco/io/stdio_file_reader.cc
Hi maintainers!
I love this terrific project.
I've built the 1.4.1 version using the latest version of Visual Studio 2019 (MSBUILD 16.9.0) for Win64.
The resulting encoder worked very well for small PLY files.
However, for files larger than 2GB, the encoder failed without error messages.
I've figured out the problem through debugging.
`ftell` was the problem: it failed to locate bytes after 2GBs. So, it cannot return the right file size.
I suggest here using `_ftelli64` explicitly, only for Win64.
Thank you, guys.
=> Support files larger than 2GB in Win64

cmake/draco_build_definitions.cmake, src/draco/io/stdio_file_reader.cc
Builds on the Windows-only fix added in
https://github.com/google/draco/pull/691
=> draco: Complete the large file support fix in the stdio reader.

src/draco/compression/mesh/mesh_sequential_decoder.cc
num_points was retrieved from a wrong location causing incorrect branch to be taken during decoding for certain input models.
=> Fixed decoding of large meshes encoded with MESH_SEQUENTIAL_ENCODING

README.md
Avoid showing build status from WIP PRs as the project build status.
=> Update the build status badge to track master.

src/draco/attributes/geometry_attribute.h
There is no need to perform the check if T is of type bool, since it is guaranteed to fit in all other integral types.
This avoids triggering a C4804 warning in Visual Studio, ie. `unsafe use of type 'bool' in operation`
=> Avoid comparing bool using the < and > operator

cmake/draco-config.cmake.template, cmake/draco_install.cmake, cmake/draco_options.cmake, src/draco/tools/install_test/CMakeLists.txt, src/draco/tools/install_test/test.py
closes https://github.com/google/draco/issues/834
=> CMake: install draco.dll in bin folder

javascript/example/README.md
The existing wording could be interpreted as that line implementing `defaults to WebAssembly if supported`, when in fact it is meant that it turns it off.
=> README: Explain better that example turns WASM off

CMakeLists.txt
/compression/attributes/attributes_decoder_interface.h was omitted,
which broke Bazel builds.
Fixes: https://github.com/google/draco/issues/912
=> Add missing include file to build.

.github/workflows/ci.yml
- Rename the existing configs that use gcc-10: add gcc-10 to the names.
- Add clang-14 configs.
=> draco: Update CI configs.

src/draco/core/decoder_buffer.h
Fixed warning regarding comparing a signed variable `bit` with unsigned `nbits`.
The value `nbits` is checked to be less then or equal to 32 in the rows above, which prevents overflow when casting to a signed type.
=> Fix signed/unsigned mismatch in decoder_buffer.h

src/draco/io/file_utils.h
This was causing failure to compile on GCC 13.
=> Add <cstdint> include to draco file_utils.h to fix GCC13 build failure.

javascript/time_draco_decode.html
after it was removed a few years ago in the update to 1.4.0
=> wasm example: add back config option for DracoDecoderModule

cmake/draco_install.cmake, cmake/draco_options.cmake
draco_options.cmake - add DRACO_INSTALL option;
draco_install.cmake - check DRACO_INSTALL before adding install rules
=> Add cmake option to enable/disable installation Issue #1029

.github/dependabot.yml
This attempts to group all security related fixes for docs/ gems into
one PR on a monthly basis.
=> add .github/dependabot.yml

docs/Gemfile.lock
notably webrick, which should address a dependabot security warning
after:
049616e docs/.ruby-version: bump version to 2.5.0
=> doc/Gemfile.lock: update deps

.github/workflows/ci.yml
Rather than gcc-10 / g++-10; the Ubuntu-latest image does not have this
installed and defaults to gcc 13.
=> ci.yml: use default gcc / g++

.github/workflows/ci.yml
windows-2019 was removed on 2025-06-30, use windows-latest. windows-2022
(latest) and windows-2025 both include Visual Studio 2022 so there
should be limited maintenance when latest is switched.
The "MinGW Makefiles" builds needed an additional update to run under
the msys shell rather than gitbash (where the executables failed to
start).
=> ci.yml: update windows image
